### ISSUE TITLE
shape issue

### ISSUE THREAD

**Issue by ausarhuy** [ntoantoan/OCR-ID-Card#1]
File "D:\Project\OCR-ID-Card-main\core\utils.py", line 63, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 40695 into shape (45,1024,1,1)

**Comment by anhnch30820** [comment]
File "D:\Project\OCR-ID-Card-main\core\utils.py", line 63, in load_weights
conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 40695 into shape (45,1024,1,1)

**Comment by anhnch30820** [comment]
File "D:\Project\OCR-ID-Card-main\core\utils.py", line 63, in load_weights
conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 40695 into shape (45,1024,1,1)

same you

**Comment by ntoantoan** [comment]
wait for me to check project

**Comment by Khirk51** [comment]
File "D:\Project\OCR-ID-Card-main\core\utils.py", line 63, in load_weights
conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 40695 into shape (45,1024,1,1)

**Comment by ntoantoan** [comment]
![image](https://user-images.githubusercontent.com/42260182/155457711-6f882956-a2be-47a3-b50f-f0f5b78faa25.png)

this is problem, please check new update

![image](https://user-images.githubusercontent.com/42260182/155457797-4e5cf029-861d-406b-b0fa-4d5b1fdfb1a3.png)
